//Подключение к базе данных mySQL
//Подключаясь к базе данных убедитесь, что все параметры введены верно.
Connection:
  //false - не использовать подключение, true - использовать подключение.
  use: false
  //Параметры подключения: address, port, database, username, password
  address: localhost
  port: 3306
  database: database
  username: username
  password: password
  //Автоматически запрашивать открытый ключ с подключаемого сервера.
  publicKeyRetrieval: false
  //Использовать протокол ssl (Secure Sockets Layer - криптографический протокол для безопасной связи).
  ssl: false
  //Минимальное количество незанятых соединений.
  minimumIdle: 2
  //Максимальное количество количество незанятых соединений.
  maximumPoolSize: 10
  //Время ожидания соединения.
  connectionTimeout: 1500
  //Идентификатор соединения (Пишется в названии соединения).
  id: 1
  //Название подключаемого сервера к базе данных (Пишется в названии соединения).
  Server: default
  //Используемая модификация соединения (Пишется в названии соединения).
  Mode: custom